require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6 # TODO ADJUST RUBY VERSION
  Include:
    - '**/*.rb'
  Exclude:
    - '**/tmp/**/*'
    - 'db/schema.rb'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Layout/LineLength:
  Max: 130

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Output:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
