x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile.test
  environment: &base-env
    DATABASE_HOST: postgres
    DATABASE_PORT: 5432
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    RAILS_ENV: test
    RAILS_LOG_TO_STDOUT: true

services:
  app:
    <<: *base
    depends_on:
      postgres:
        condition: service_healthy
      chrome:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      <<: *base-env
      CI: true
      CHROME_URL: http://chrome:9222
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:-}

  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: podi_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  chrome:
    image: browserless/chrome:latest
    ports:
      - 9222:9222
    shm_size: 2gb
    environment:
      CONNECTION_TIMEOUT: 600000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres:
