x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile.test
  environment: &base-env
    DATABASE_HOST: postgres
    DATABASE_PORT: 5432
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    RAILS_ENV: test
    RAILS_LOG_TO_STDOUT: true

services:
  app:
    <<: *base
    depends_on:
      postgres:
        condition: service_healthy
      chrome:
        condition: service_healthy
    ports:
      - "3001:3000"
    volumes:
      - .:/rails
    environment:
      <<: *base-env
      CAPYBARA_SERVER_PORT: 3001
      CI: true
      CHROME_URL: http://chrome:4444/wd/hub
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:-}

  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: podi_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2gb
    volumes:
      - .:/rails:cached
    environment:
      SE_NODE_MAX_SESSIONS: 4
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres:
