x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile
  stdin_open: true
  tty: true
  volumes:
    - .:/rails
    - rails_cache:/rails/tmp/cache
    - node_modules:/rails/node_modules
  env_file:
    - .env
  environment:
    - DATABASE_HOST=postgres
    - DATABASE_PORT=5432
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=postgres
    - RAILS_LOG_LEVEL=debug
    - RAILS_ENV=production
    - REDIS_URL=redis://redis:6379/0
    - DEFAULT_URL_HOST=www.wartenberger.de
  depends_on:
    postgres:
      condition: service_healthy

services:
  app:
    <<: *base
    ports:
      - "3000:80"
    healthcheck:
      test: curl --fail http://0.0.0.0:80/up || exit 1
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:17
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
volumes:
  postgres:
  bundle:
  rails_cache:
  node_modules:
