local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

aws:
  service: S3
  access_key_id: <%= Rails.application.config.aws_access_key %>
  secret_access_key: <%= Rails.application.config.aws_secret_key %>
  bucket: <%= Rails.application.config.aws_bucket_name %>
  region: <%= Rails.application.config.aws_s3_region %>

cloudinary:
  service: Cloudinary
  cloud_name: <%= Rails.application.config.cloudinary_cloud_name %>
  api_key: <%= Rails.application.config.cloudinary_api_key %>
  api_secret: <%= Rails.application.config.cloudinary_api_secret %>
  secure: true
  cdn_subdomain: true
