name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: |
        docker-compose -f docker-compose.yml up -d --build
        docker-compose -f docker-compose.yml ps
        docker-compose -f docker-compose.yml logs

    - name: prepare
      run: |
        docker-compose -f docker-compose.yml ps
        docker-compose -f docker-compose.yml logs
        docker-compose -f docker-compose.yml exec app bin/rails db:create --trace
        docker-compose -f docker-compose.yml exec app bin/rails db:test:prepare --trace

    - name: Run rubocop
      run: docker-compose -f docker-compose.yml exec app bundle exec rubocop

    - name: Run tests
      run: docker-compose -f docker-compose.yml exec app bundle exec rspec .

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.yml down
